#!/bin/sh

cp /etc/nixos/hardware-configuration.nix ~/satrix/nix/hardware-configuration.nix

cd ~/satrix/nix/

nix flake update

git add . && git commit -m 's'

sudo nixos-rebuild switch --upgrade --flake .#satrix

nix store optimise
